apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  SUPER_PASSWORD: {{ default (randAlphaNum 10) .Values.superPassword | b64enc | quote }}
